diabetes_app/diabetes_app/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from glycemic_index_app.views import *
from django.urls import path, include

app_name = 'glycemic_index_app'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gi-webapp/', include(('glycemic_index_app.urls', 'glycemic_index_app'), namespace="glycemic_index_app")),
    path('api/notemodel/<int:pk>/', NoteModelDetailView.as_view(), name='note-detail'),
    path('api/get-table-data/', NoteModelListView.as_view(), name='note-list'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diabetes_app/glycemic_index_app/urls.py
from django.urls import path

from . import views
from .views import *

urlpatterns = [
    path('', index, name='main'),
    path('note/<int:pk>/', detail, name='note_detail'),
    path('add/', add, name='add'),
    path('stat/', stat, name='stat'),
    path('login/', login_view, name='login'),
    path('personal_data/', personal_data, name='personal_data'),
    path('settings/', setts, name='setts'),
    path('signup/', signup, name='signup'),
    path('logout/', logout_view, name='logout'),
    path('delete/<int:pk>/', delete_record, name='delete_record'),
]

diabetes_app/glycemic_index_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator

class CustomUser(AbstractUser):
    rcg = models.TextField(blank=True, default='0.01|0.02|0.03|0.04|0.05|0.06|0.07|0.08|0.09|0.1')
    absorption_time = models.TextField(blank=True, default='100|90|80|70|60|50|40|30|20|10')
    bu_index = models.TextField(blank=True, default='2.5')

    def __str__(self):
        return self.username

class Note(models.Model):
    title = models.CharField(max_length=300)
    content = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    glycemia = models.FloatField()
    bread_units = models.FloatField(blank=True)
    glycemic_index = models.CharField(max_length=500)
    general_gi = models.FloatField()
    general_rcg = models.FloatField()
    graph = models.TextField()
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Note'
        verbose_name_plural = 'Notes'
        ordering = ['-created_at']

# class Statistics(models.Model):
#     average_glycemia = models.FloatField(blank=True)
#     average_bu = models.FloatField(blank=True)
#     average_gi = models.FloatField(blank=True)
#     average_rcg = models.FloatField(blank=True)
#     graph_glycemia = models.TextField(blank=True)
#     graph_bu = models.TextField(blank=True)
#     graph_gi = models.TextField(blank=True)
#     graph_rcg = models.TextField(blank=True)
#     user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)  

diabetes_app/glycemic_index_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator

from .models import Note, CustomUser

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        User = get_user_model()
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'content', 'glycemia', 'bread_units', 'glycemic_index', 'general_gi', 'general_rcg', 'graph']
        widgets = {
            'title': forms.TextInput(attrs={
                'id': 'form-name',
                'placeholder': 'Название записи',
                'name': 'title',
                'type': 'text',
                'required': ''
            }),
            'content': forms.Textarea(attrs={
                'id': 'form-desc',
                'placeholder': 'Описание',
                'name': 'desc',
                'type': 'text',
                'required': ''
            }),
            'glycemia': forms.TextInput(attrs={
                'id': 'form-glycemia',
                'placeholder': 'Ммоль/л',
                'name': 'glycemia',
                'type': 'number',
                'required': '',
                'min': '1',
                'max': '25',
                'step': '0.01'
            }),
            'bread_units': forms.TextInput(attrs={
                'id': 'form-XE',
                'placeholder': 'ХЕ',
                'name': 'bu',
                'type': 'number',
                'required': '',
                'step': '0.01'
            }),
            'glycemic_index': forms.HiddenInput(attrs={
                'id': 'actual-gi',
            }),
            'general_gi': forms.HiddenInput(attrs={
                'id': 'avg-gi',
            }),
            'general_rcg': forms.HiddenInput(attrs={
                'id': 'avg-rcg',
            }),
            'graph': forms.HiddenInput(attrs={
                'id': 'graph',
            }),
        }

class EditingForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'content', 'glycemia', 'bread_units', 'glycemic_index', 'general_gi', 'general_rcg', 'graph']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'detail-input title-input',
                'placeholder': 'Название записи',
                'name': 'title',
                'type': 'text',
                'required': ''
            }),
            'content': forms.Textarea(attrs={
                'class': 'detail-input main-desc',
                'placeholder': 'Описание',
                'name': 'desc',
                'required': ''
            }),
            'glycemia': forms.TextInput(attrs={
                'class': 'detail-glycemia detail-input',
                'id': 'form-glycemia',
                'placeholder': 'Ммоль/л',
                'name': 'glycemia',
                'type': 'number',
                'required': '',
                'min': '1',
                'max': '25',
                'step': '0.01'
            }),
            'bread_units': forms.TextInput(attrs={
                'class': 'detail-glycemia detail-input',
                'placeholder': 'ХЕ',
                'id': 'form-XE',
                'name': 'bread_units',
                'type': 'number',
                'required': '',
                'step': '0.01'
            }),
            'glycemic_index': forms.HiddenInput(attrs={
                'id': 'actual-gi',
            }),
            'general_gi': forms.HiddenInput(attrs={
                'id': 'avg-gi',
            }),
            'general_rcg': forms.HiddenInput(attrs={
                'id': 'avg-rcg',
            }),
            'graph': forms.HiddenInput(attrs={
                'id': 'graph',
            }),
        }

class UserEditingForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['rcg', 'absorption_time', 'bu_index']
        widgets = {
            'bu_index': forms.TextInput(attrs={
                'id': 'bu-index',
                'placeholder': 'ммоль/л',
                'name': 'bu_index',
                'type': 'number',
                'required': '',
                'min': '0.1',
                'max': '5',
                'step': '0.001'
            }),
            'rcg': forms.HiddenInput(attrs={
                'id': 'general-rcg',
                'name': 'general-rcg',
                'required': '',
            }),
            'absorption_time': forms.HiddenInput(attrs={
                'id': 'general-timein',
                'name': 'general-timein',
                'required': '',
            }),
        }

diabetes_app/glycemic_index_app/views.py
from pyexpat.errors import messages
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render

from .models import CustomUser, Note
from .forms import SignUpForm, EditingForm, UserEditingForm

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import NoteSerializer
from django.contrib.auth.decorators import login_required
from django.db.models import Avg

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout, get_user_model
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import NoteForm

class NoteModelDetailView(APIView):
    def get(self, request, pk):
        try:
            item = Note.objects.get(pk=pk)
            serializer = NoteSerializer(item)
            return Response(serializer.data)
        except Note.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        
class NoteModelListView(APIView):
    def get(self, request):
        try:
            user = request.user  # Получаем текущего пользователя
            data = list(Note.objects.filter(user=user).values())  # Получить все данные как словарь
            return JsonResponse(data, safe=False)
        except Note.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

@login_required(login_url='glycemic_index_app:login')
def index(request):
    # Получаем поисковый запрос из GET параметров
    query = request.GET.get('q')

    # Фильтруем записи по пользователю и, если есть запрос, по заголовку
    if query:
        notes = Note.objects.filter(user=request.user, title__icontains=query)
    else:
        notes = Note.objects.filter(user=request.user)

    # Подготовка контекста для шаблона
    context = {
        'notes': notes,
        'title': 'Список записей',
        'name': 'main'
    }

    # Рендеринг шаблона с контекстом
    return render(request, 'glycemic_index_app/components/main.html', context=context)

@login_required(login_url='glycemic_index_app:login')
def detail(request, pk):
    notes = get_object_or_404(Note, pk=pk)
    if request.method == 'POST':
        form = EditingForm(request.POST, instance=notes)
        if form.is_valid():
            form.save()
            return redirect('glycemic_index_app:main')  # перенаправление на страницу с записью после сохранения
    else:
        form = EditingForm(instance=notes)
    context = {'notes': notes, 'list': notes.glycemic_index.split(","), 'title': 'Запись', 'name': 'detail', 'form': form}
    return render(request, 'glycemic_index_app/components/detail.html', context=context)

def delete_record(request, pk):
    record = get_object_or_404(Note, pk=pk)
    record.delete()
    return redirect(reverse('glycemic_index_app:main'))

@login_required(login_url='glycemic_index_app:login')
def add(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)  # Сначала не сохраняем в базу данных
            note.user = request.user  # Назначаем текущего пользователя
            note.save()  # Сохраняем объект в базу данных
            return redirect('glycemic_index_app:main')  # замените на ваш путь
    else:
        form = NoteForm()
    context = {'title': 'Добавить запись', 'name': 'add', 'form': form}
    return render(request, 'glycemic_index_app/components/add.html', context=context)

@login_required(login_url='glycemic_index_app:login')
def stat(request):
    user = request.user
    glycemia_average = Note.objects.filter(user=user).aggregate(Avg('glycemia'))['glycemia__avg']
    bu__average = Note.objects.filter(user=user).aggregate(Avg('bread_units'))['bread_units__avg']
    gi_average = Note.objects.filter(user=user).aggregate(Avg('general_gi'))['general_gi__avg']
    rcg_average = Note.objects.filter(user=user).aggregate(Avg('general_rcg'))['general_rcg__avg']
    context = {'title': 'Статистика', 
               'name': 'stat', 
               'glycemia__avg': glycemia_average, 
               'bread_units__avg': bu__average, 
               'general_gi__avg': gi_average, 
               'general_rcg__avg': rcg_average,}
    return render(request, 'glycemic_index_app/components/stat.html', context=context)

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = authenticate(request, username=request.POST["username"],
                            password=request.POST["password"])
            if user is not None:
                login(request, user)
                return redirect('glycemic_index_app:main')
    else:
        form = AuthenticationForm()
    context = {'title': 'Вход', 'name': 'login', 'form': form}
    return render(request, 'glycemic_index_app/components/login.html', context=context)

def logout_view(request):
    logout(request)
    return redirect('glycemic_index_app:main')

@login_required(login_url='glycemic_index_app:login')
def personal_data(request):
    user = request.user
    rcg = user.rcg.split("|")
    abcTime = user.absorption_time.split("|")
    combined_array = list(zip(rcg, abcTime))

    if request.method == 'POST':
        user_form = UserEditingForm(request.POST, instance=user)
        if user_form.is_valid():
            user_form.save()
            return redirect('glycemic_index_app:main')
    else:
        user_form = UserEditingForm(instance=user)
    context = {'title': 'Личные данные', 'name': 'personal_data', 'form': user_form, 'rcgTimeIn': combined_array}
    return render(request, 'glycemic_index_app/components/personal_data.html', context=context)

@login_required(login_url='glycemic_index_app:login')
def setts(request):
    context = {'title': 'Настройки', 'name': 'settings'}
    return render(request, 'glycemic_index_app/components/settings.html', context=context)

def signup(request):
    print(request.method)
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # Обновляем экземпляр пользователя с помощью данных из формы
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('glycemic_index_app:main')
        else:
            for field in form:
                print("Field Error:", field.name,  field.errors)
    else:
        form = SignUpForm()
    context = {'title': 'Регистрация', 'name': 'signup', 'form': form}
    return render(request, 'glycemic_index_app/components/signup.html', context=context)

diabetes_app/glycemic_index_app/templates/glycemic_index_app/components/add.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}

{% block link %}
<link rel="stylesheet" href="{% static 'glycemic_index_app/css/add.css' %}">
{% endblock %}

{% block main %}
<div class="main-inner add">
    <span class="main-title">Добавить запись</span>
    <h1 class="main-inner-title">Новая запись</h1>
    <form action="" id="add-form" method="post">
        {% csrf_token %}
        <div class="form-item">
            <span class="form-title">Название*</span>
            {{ form.title }}
        </div>
        <div class="form-item">
            <span class="form-title">Описание*</span>
            {{ form.content }}
        </div>
        <div class="form-flex">
            <div class="form-item glycemia">
                <span class="form-title">Гликемия (сахар в крови)*</span>
                {{ form.glycemia }}
            </div>
            <div class="form-item">
                <span class="form-title">Хлебные единицы*</span>
                {{ form.bread_units }}
            </div>
        </div>
        <!-- {% if form.errors %}
        <div class="error">
            {{ form.errors }}
        </div>
        {% endif %} -->
        <div class="form-item" id="note-GI-list">
            <div style="display: flex;">
                <span class="form-title">ГИ продукта(-ов)*</span>
                <button class="form-add-button" onclick="addFn()" type="button">
                    <svg width="21" height="21" viewBox="0 0 21 21" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <circle cx="10.5" cy="10.5" r="10" stroke="var(--color-text)" />
                        <path
                            d="M11.1923 6.69231C11.1923 6.30937 10.8829 6 10.5 6C10.1171 6 9.80769 6.30937 9.80769 6.69231V9.80769H6.69231C6.30937 9.80769 6 10.1171 6 10.5C6 10.8829 6.30937 11.1923 6.69231 11.1923H9.80769V14.3077C9.80769 14.6906 10.1171 15 10.5 15C10.8829 15 11.1923 14.6906 11.1923 14.3077V11.1923H14.3077C14.6906 11.1923 15 10.8829 15 10.5C15 10.1171 14.6906 9.80769 14.3077 9.80769H11.1923V6.69231Z"
                            fill="var(--color-text)" />
                    </svg>
                </button>
            </div>
            <input required type="number" min="0" max="150" placeholder="Число" class="form-GI" id="form-GI">
        </div>
        {{ form.glycemic_index }}
        {{ form.general_gi }}
        {{ form.general_rcg }}
        {{ form.graph }}
        <input type="hidden" id="user_rcg" value="{{ user.rcg }}">
        <input type="hidden" id="user_timeIn" value="{{ user.absorption_time }}">
        <input type="hidden" id="user_buIndex" value="{{ user.bu_index }}">
        <!-- <div class="conclusion-info">
            <div class="conclusion-line">
                <span class="conclusion-title">Общий ГИ:</span>
                <span>30</span>
            </div>
            <div class="conclusion-line">
                <span class="conclusion-title">Общий СИГ:</span>
                <span>0.096 ммоль/л/мин</span>
            </div>
        </div> -->
        <button class="form-button" type="submit">Добавить</button>
    </form>
    <div class="messages">
        {% for field in form %}
        {% if field.errors %}
        <div class="message">{{ field.label }}: {{ field.errors|striptags }}</div>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'glycemic_index_app/javaScript/giCalculator.js' %}"></script>
<script src="{% static 'glycemic_index_app/javaScript/giAddButton.js' %}"></script>
{% endblock %}

diabetes_app/glycemic_index_app/templates/glycemic_index_app/components/detail.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}

{% block link %}
<link rel="stylesheet" href="{% static 'glycemic_index_app/css/detail.css' %}">
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
{% endblock %}

{% block main %}
<div class="main-inner">
    <span class="main-title">Общий список > {{ notes.title }}</span>
    <div class="main-note">
        <form action="" id="add-form" method="post">
            {% csrf_token %}
            {{ form.title }}
            <div class="note-date">{{ notes.created_at|date:"d.m.Y, H:i" }}</div>
            {{ form.content }}
            <div class="note-flex">
                <span class="note-glycemia"><b>Гликемия:</b> {{ form.glycemia }}</span>
                <span class="note-xe"><b>ХЕ:</b> {{ form.bread_units }}</span>
            </div>  
            <div class="note-GI">
                <div class="note-GI-title">
                    <h3>ГИ продуктов</h3>
                    <button class="note-add-button" onclick="addFn()" type="button">
                        <svg width="21" height="21" viewBox="0 0 21 21" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <circle cx="10.5" cy="10.5" r="10" stroke="var(--color-text)" />
                            <path
                                d="M11.1923 6.69231C11.1923 6.30937 10.8829 6 10.5 6C10.1171 6 9.80769 6.30937 9.80769 6.69231V9.80769H6.69231C6.30937 9.80769 6 10.1171 6 10.5C6 10.8829 6.30937 11.1923 6.69231 11.1923H9.80769V14.3077C9.80769 14.6906 10.1171 15 10.5 15C10.8829 15 11.1923 14.6906 11.1923 14.3077V11.1923H14.3077C14.6906 11.1923 15 10.8829 15 10.5C15 10.1171 14.6906 9.80769 14.3077 9.80769H11.1923V6.69231Z"
                                fill="var(--color-text)" />
                        </svg>
                    </button>
                </div>
                <div class="note-GI-list" id="note-GI-list">
                    {% for item in list %}
                        <div class="form-GI-wrapper">
                            <input type="number" min="0" max="150" name="glycemic-index" class="form-GI" value="{{ item }}">
                            <button class="minus-button" onclick="delNode(this)" type="button"></button>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="conclusion-info">
                <div class="conclusion-line">
                    <span class="conclusion-title">Общий ГИ:</span>
                    <span>{{ notes.general_gi }}</span>
                </div>
                <div class="conclusion-line">
                    <span class="conclusion-title">Общий СИГ:</span>
                    <span>{{ notes.general_rcg }}</span>
                </div>
            </div>
            <div id="curve_chart" style="max-width: 100%;"></div>
            {{ form.glycemic_index }}
            {{ form.general_gi }}
            {{ form.general_rcg }}
            {{ form.graph }}
            <input type="hidden" id="user_rcg" value="{{ user.rcg }}">
            <input type="hidden" id="user_timeIn" value="{{ user.absorption_time }}">
            <input type="hidden" id="user_buIndex" value="{{ user.bu_index }}">
            <div class="buttons">
                <button class="note-button" type="submit">Сохранить</button>
                <button id="openModalBtn" type="button">Удалить</button>
            </div>
        </form>
        <div id="myModal" class="modal">

            <!-- Контент модального окна -->
            <div class="modal-content">
                <h2>Вы уверены что хотите удалить запись?</h2>
                <p>После удаления запись будет невозозможно восстановить.</p>
                <a href="{% url 'glycemic_index_app:delete_record' notes.pk %}" class="delete-button">Удалить</a>
                <button class="cancel-button close">Отмена</button>
            </div>
    
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'glycemic_index_app/javaScript/giAddButton.js' %}"></script>
<script src="{% static 'glycemic_index_app/javaScript/giCalculator.js' %}"></script>
<script src="{% static 'glycemic_index_app/javaScript/detailPageAPI.js' %}"></script>
<script src="{% static 'glycemic_index_app/javaScript/modalWindow.js' %}"></script>
{% endblock %}

diabetes_app/glycemic_index_app/templates/glycemic_index_app/components/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List</title>
    <link rel="stylesheet" href="{% static 'glycemic_index_app/css/default.css' %}">
    <link rel="stylesheet" href="{% static 'glycemic_index_app/css/login.css' %}">
    <script src="https://kit.fontawesome.com/c8ea1a53b8.js" crossorigin="anonymous"></script>
</head>

<body>
    <div class="container">
        <div class="extra-info">
        </div>
        <div class="signup-form">
            <form class="signup-form-inner" method="post" action="{% url 'glycemic_index_app:login' %}">
                {% csrf_token %}
                <input type="checkbox" id="theme" class="theme-toggle">
                <!-- <label for="theme" class="theme-button"></label> -->
                <a href="javascript:history.back()" class="back-link">Назад</a>
                <h1>Войти</h1>
                {% if form.non_field_errors %}
                    <div class="errors">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
                <div class="form-input flex">
                    <div>Email</div>
                    <input type="text" name="username" placeholder="Ваш логин">
                </div>
                <div class="form-input flex">
                    <div>Пароль</div>
                    <input type="password" name="password" placeholder="Ваш пароль">
                </div>
                <button class="form-button" type="submit">Войти</button>
                <p class="form-link">Не зарегистрированы? <a
                        href="{% url 'glycemic_index_app:signup' %}">Зарегистрироваться</a></p>
            </form>
        </div>
    </div>
    <script src="{% static 'glycemic_index_app/javaScript/switchstyle.js' %}"></script>
</body>

</html>

diabetes_app/glycemic_index_app/templates/glycemic_index_app/components/main.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}

{% block link %}
<link rel="stylesheet" href="{% static 'glycemic_index_app/css/main.css' %}">
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
{% endblock %}

{% block main %}
<div class="div-title">Отчёт</div>
<div class="top-side">
    <button class="list-button show">Показать</button>
    <button class="list-button hide">Скрыть</button>
    <div class="list active">
        <div class="top-card">
            <div id="glycemia-chart"></div>
        </div>
        <div class="top-card">
            <div id="glycemic-index-chart"></div>
        </div>
        <div class="top-card text">
            <div class="top-card-text">
                <div class="icon-wrapper">
                    <svg class="main-page-advice-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M272 384c9.6-31.9 29.5-59.1 49.2-86.2c0 0 0 0 0 0c5.2-7.1 10.4-14.2 15.4-21.4c19.8-28.5 31.4-63 31.4-100.3C368 78.8 289.2 0 192 0S16 78.8 16 176c0 37.3 11.6 71.9 31.4 100.3c5 7.2 10.2 14.3 15.4 21.4c0 0 0 0 0 0c19.8 27.1 39.7 54.4 49.2 86.2l160 0zM192 512c44.2 0 80-35.8 80-80l0-16-160 0 0 16c0 44.2 35.8 80 80 80zM112 176c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-61.9 50.1-112 112-112c8.8 0 16 7.2 16 16s-7.2 16-16 16c-44.2 0-80 35.8-80 80z"/></svg>
                </div>
                <h3>Сочетайте углеводы с белками и жирами</h3>
            </div>
            <p>Белки и жиры замедляют всасывание углеводов, что помогает контролировать скачки глюкозы. Например, можно
                добавить орехи к фруктам или съесть рыбу с овощами.</p>
        </div>
        <div class="top-card text">
            <div class="top-card-text">
                <div class="icon-wrapper">
                    <svg class="main-page-advice-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M272 384c9.6-31.9 29.5-59.1 49.2-86.2c0 0 0 0 0 0c5.2-7.1 10.4-14.2 15.4-21.4c19.8-28.5 31.4-63 31.4-100.3C368 78.8 289.2 0 192 0S16 78.8 16 176c0 37.3 11.6 71.9 31.4 100.3c5 7.2 10.2 14.3 15.4 21.4c0 0 0 0 0 0c19.8 27.1 39.7 54.4 49.2 86.2l160 0zM192 512c44.2 0 80-35.8 80-80l0-16-160 0 0 16c0 44.2 35.8 80 80 80zM112 176c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-61.9 50.1-112 112-112c8.8 0 16 7.2 16 16s-7.2 16-16 16c-44.2 0-80 35.8-80 80z"/></svg>
                </div>
                <h3>Избегайте сильно обработанных продуктов</h3>
            </div>
            <p>Обработанные продукты, такие как сладкие напитки и выпечка, часто имеют высокий ГИ, даже если в них
                добавлены
                полезные ингредиенты. Предпочитайте цельные продукты с минимальной обработкой.</p>
        </div>
    </div>
</div>
<div class="div-title">Список записей</div>
<div class="main-list">
    {% for item in notes %}
    <div class="card">
        <h1 class="card-title">{{ item.title }}</h1>
        <div class="card-date-list">
            <span class="card-date">{{ item.created_at|date:"d.m.Y, H:i" }}</span>
        </div>
        <p>{{ item.content|slice:":100" }}{% if item.content|length > 100 %}...{% endif %}</p>
        <div class="card-info-list">
            <div class="card-info-list__item">Гликемия: {{ item.glycemia }}</div>
            <div class="card-info-list__item">Общий ГИ: {{ item.general_gi }}</div>
            <div class="card-info-list__item">Общий СИГ: {{ item.general_rcg }}</div>
        </div>
        <a href="{% url 'glycemic_index_app:note_detail' item.pk %}">Подробнее</a>
    </div>
    {% endfor %}
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'glycemic_index_app/javaScript/glycemiaAPI.js' %}"></script>
<script src="{% static 'glycemic_index_app/javaScript/glycemicIndexAPI.js' %}"></script>
<script src="{% static 'glycemic_index_app/javaScript/mainPageButton.js' %}"></script>
{% endblock %}